{
 "title": "Plex Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Download",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "LINUX_SERVERS" },
     "host": { "filter": "PLEX_SERVER" },
     "item": {
      "filter": "Incoming network traffic on ens192"
     },
     "measurement": "bandwidth",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "download_bitrate" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "interface", "operator": "=", "value": "outside" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Upload",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "LINUX_SERVERS" },
     "host": { "filter": "PLEX_SERVER" },
     "item": {
      "filter": "Outgoing network traffic on ens192"
     },
     "measurement": "bandwidth",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "upload_bitrate" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "interface", "operator": "=", "value": "outside" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Plex CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [],
        "name": "sumSeries",
        "params": []
       },
       "params": [],
       "text": "sumSeries()"
      }
     ],
     "group": { "filter": "LINUX_SERVERS" },
     "host": { "filter": "PLEX_SERVER" },
     "item": { "filter": "/CPU (?!.*(idle))/" },
     "measurement": "Plex",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "CPU Utilization" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "server", "operator": "=", "value": "Plex" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "IO_Wait",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "LINUX_SERVERS" },
     "host": { "filter": "PLEX_SERVER" },
     "item": { "filter": "CPU iowait time" },
     "measurement": "Storage Servers",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "IO_Wait" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "server", "operator": "=", "value": "SAN3" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Plex Web Threads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "LINUX_SERVERS" },
     "host": { "filter": "PLEX_SERVER" },
     "item": { "filter": "Plex - Number of web threads" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "current_streams" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "type", "operator": "=", "value": "stream_count" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Req. Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "pending" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Request_Counts" }
     ]
    }
   ]
  },
  {
   "title": "WebSock msg /s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "LINUX_SERVERS" },
     "host": { "filter": "PLEX_SERVER" },
     "item": {
      "filter": "Plex - Websocket messages per second"
     },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "current_streams" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "type", "operator": "=", "value": "stream_count" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Data Transferred (Today)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "LINUX_SERVERS" },
     "host": { "filter": "PLEX_SERVER" },
     "item": { "filter": "Total daily bandwidth" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "current_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "stream_count" }
     ]
    }
   ]
  },
  {
   "title": "Total Data Transferred (Month)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "LINUX_SERVERS" },
     "host": { "filter": "PLEX_SERVER" },
     "item": { "filter": "Total monthly bandwidth" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "current_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "stream_count" }
     ]
    }
   ]
  },
  {
   "title": "Plex - Total Stream/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Plex Media Server" },
     "host": { "filter": "PLEX_SERVER" },
     "item": { "filter": "Plex - Total streams" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
     "tags": [
      { "key": "type", "operator": "=", "value": "stream_count" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Plex - Transcode/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "LINUX_SERVERS" },
     "host": { "filter": "PLEX_SERVER" },
     "item": { "filter": "Plex - Transcode streams" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "current_streams" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "type", "operator": "=", "value": "stream_count" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Plex - Direct Play/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Special",
        "defaultParams": [ "avg" ],
        "name": "consolidateBy",
        "params": [
         {
          "name": "type",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "max" ],
       "text": "consolidateBy(max)"
      }
     ],
     "group": { "filter": "LINUX_SERVERS" },
     "host": { "filter": "PLEX_SERVER" },
     "item": { "filter": "Plex - Direct play streams" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "current_streams" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "type", "operator": "=", "value": "stream_count" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Plex - Direct Stream/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Special",
        "defaultParams": [ "avg" ],
        "name": "consolidateBy",
        "params": [
         {
          "name": "type",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "max" ],
       "text": "consolidateBy(max)"
      }
     ],
     "group": { "filter": "LINUX_SERVERS" },
     "host": { "filter": "PLEX_SERVER" },
     "item": { "filter": "Plex - Direct streams" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "current_streams" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "type", "operator": "=", "value": "stream_count" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Missing Available Movies",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 3 },
   "targets": [
    {
     "measurement": "Radarr",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "Movie" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Missing_Available" },
      { "condition": "AND", "key": "server", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download",
     "application": { "filter": "" },
     "group": { "filter": "LINUX_SERVERS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "host": { "filter": "PLEX_SERVER" },
     "item": {
      "filter": "Incoming network traffic on ens192"
     },
     "measurement": "bandwidth",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "download_bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "interface", "operator": "=", "value": "outside" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "alias": "Upload",
     "application": { "filter": "" },
     "group": { "filter": "LINUX_SERVERS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "host": { "filter": "PLEX_SERVER" },
     "item": {
      "filter": "Outgoing network traffic on ens192"
     },
     "measurement": "bandwidth",
     "options": {
      "showDisabledItems": false
     },
     "select": [
      [
       { "params": [ "upload_bitrate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "interface", "operator": "=", "value": "outside" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 6 },
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_region_code",
     "groupBy": [
      { "params": [ "region_code" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "location" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Movies in Queue",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
   "targets": [
    {
     "measurement": "Radarr",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       { "params": [ "Movie" ], "type": "alias" }
      ],
      [
       { "params": [ "protocol_id" ], "type": "field" },
       { "params": [ "T" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Queue" }
     ]
    }
   ]
  },
  {
   "title": "Users Online",
   "type": "table",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 14 },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "SELECT \"name\", \"title\", \"quality\", \"video_decision\", \"quality_profile\", \"platform\", \"product_version\", \"location\" FROM \"Tautulli\" WHERE (\"type\" = 'Session') AND $timeFilter GROUP BY \"session_key\"",
     "select": [
      [
       { "params": [ "name" ], "type": "field" }
      ],
      [
       { "params": [ "title" ], "type": "field" }
      ],
      [
       { "params": [ "quality" ], "type": "field" }
      ],
      [
       { "params": [ "transcode_decision" ], "type": "field" }
      ],
      [
       { "params": [ "quality_profile" ], "type": "field" }
      ],
      [
       { "params": [ "platform" ], "type": "field" }
      ],
      [
       { "params": [ "product_version" ], "type": "field" }
      ],
      [
       { "params": [ "location" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "TV Shows on Today",
   "type": "table",
   "gridPos": { "h": 14, "w": 4, "x": 16, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sonarrId" ], "type": "tag" }
     ],
     "measurement": "Sonarr",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       { "params": [ "TV Show" ], "type": "alias" }
      ],
      [
       { "params": [ "sxe" ], "type": "field" },
       { "params": [ "S/E" ], "type": "alias" }
      ],
      [
       { "params": [ "downloaded" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Today" }
     ]
    }
   ]
  },
  {
   "title": "Missing TV Shows (Last 7 Days)",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sonarrId" ], "type": "tag" }
     ],
     "measurement": "Sonarr",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       { "params": [ "TV Show" ], "type": "alias" }
      ],
      [
       { "params": [ "sxe" ], "type": "field" },
       { "params": [ "S/E" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Missing_Days" }
     ]
    }
   ]
  },
  {
   "title": "TV Shows in Queue",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 21 },
   "targets": [
    {
     "measurement": "Sonarr",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       { "params": [ "TV Show" ], "type": "alias" }
      ],
      [
       { "params": [ "sxe" ], "type": "field" },
       { "params": [ "S/E" ], "type": "alias" }
      ],
      [
       { "params": [ "protocol_id" ], "type": "field" },
       { "params": [ "T" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Queue" }
     ]
    }
   ]
  }
 ]
}